import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "모두의 여행",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-gray-100">
        <main className="max-w-md w-full justify-self-center bg-zinc-900 min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
